### PR TITLE
manifest: signing commits using gpg

### LINKED ISSUE #1: Signing commits using GPG
SmartGit cannot sign commits:

```
Commit: gpg failed to sign the data failed to write commit object
	/home/x80486/Workshop/some-repo> git commit --cleanup=whitespace --file=/tmp/smartgit-17819135483608894911tmp/commit-14493487505562511998.tmp
	gpg failed to sign the data
	failed to write commit object
```

This works fine on the non-Flatpak'ed version. I'm not super-familiar with GPG, but it looks like SmartGit does not have access (eventually) to the `gpg-agent` running in the host. Maybe installing `GPGTools`?

### PR DESCRIPTION
**Pull request by x80486**
Closes #1

### CODE REVIEW

**Comment by x80486** [comment]
> **REMINDER:** Tweak `cleanup` elements.

**Comment by x80486** [comment]
bot build

**Comment by Erick555** [comment]
@x80486 gnupg is in Platform and redundant. You need proper permissions instead:
```
--filesystem=~/.gnupg
--filesystem=xdg-run/gnupg:ro
--talk-name=org.gnome.keyring.SystemPrompter
```

**Comment by x80486** [comment]
Ah! Didn't know...let my try with that. I just included it because `SmartGit` couldn't find it as `gpg` alone in the **Signing** section.

image

**Comment by x80486** [comment]
...and you nailed it! [Works](https://github.com/x80486/test-gnupg/commits/master/) perfect! Thanks @Erick555 :tada:

**Pull request merged**
